Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Quizz_KamiliaSbahi.Models;

namespace Quizz_KamiliaSbahi.Controllers
{
    public class ClientController : Controller
    {
        DataClassesDataContext DB = new DataClassesDataContext();
        // GET: Client
        public ActionResult Index()
        {
            return View();
        }

        // GET: Client/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Client/Create
        public ActionResult PrendreRDV()
        {
            return View();
        }

        // POST: Client/Create
        [HttpPost]
        public ActionResult PrendreRDV(RDV collection)
        {
            try
            {
                // TODO: Add insert logic here
                DB.RDVs.InsertOnSubmit(collection);
                DB.SubmitChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Client/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Client/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Client/Delete/5
        public ActionResult Delete(int id)
        {
            var databyid = DB.RDVs.Single(x => x.IdRDV == id);
            return View(databyid);
        }

        // POST: Client/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, RDV collection)
        {
            try
            {
                // TODO: Add delete logic here
                var data = DB.RDVs.Single(x => x.IdRDV == id);
                DB.RDVs.DeleteOnSubmit(data);
                DB.SubmitChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Quizz_KamiliaSbahi.Models;

namespace Quizz_KamiliaSbahi.Controllers
{
    public class LoginController : Controller
    {
        DataClassesDataContext DB = new DataClassesDataContext();
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginClass login)
        {
            SearchUser SS = new SearchUser();
            string pass = SS.SearchU(login);

            if (pass == login.Password)
            {
                var usrE = DB.Clients.Where(x => x.Username == login.Username && x.Password == login.Password).FirstOrDefault();
                if (usrE != null)
                {
                    FormsAuthentication.SetAuthCookie(usrE.Username, false);
                    Session["UserID"] = login.IdClient.ToString();
                    Session["UserPrenom"] = login.Nom.ToString();
                    Session["Password"] = login.Password.ToString();
                }
                return View("Index", "Enseignant");
                //return View("~/Views/LoginUser/Login.cshtml", Item);

            }
            else
            {
                ViewBag.data = "invalid user";
                return View("Login", "Login");
            }
        }

        // GET: Login/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Login/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Login/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Login/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Login/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Login/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Login/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Login/Login.cshtml
@model Quizz_KamiliaSbahi.Models.LoginClass

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm("Index","Client")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LoginClass</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}